logFilters:
  - code: YN0013
    level: discard

nodeLinker: node-modules

nmSelfReferences: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-aws-codeartifact.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-aws-codeartifact/v0.10.1/bundles/@yarnpkg/plugin-aws-codeartifact.js"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
